### ISSUE TITLE
A parameter on invs (cats and autocats in the future) to sort the element order

### ISSUE THREAD

**Issue by IdaeChop** [rayzchen/pyeod#23]
Self explanatory, it would sort by Tree Size, Alphabetical Order (please make it actually sort AaBb...YyZz instead of AB...YZab..yz), Creation Date, so on.

**Comment by Cheesy-Brik** [comment]
Shouldn't be a param. Maybe a drop down menu to change sorting.

**Comment by Cheesy-Brik** [comment]
This is done for invs, make a separate issue when cats are done
