### ISSUE TITLE
Using = instead of !s breaks the polls

### ISSUE THREAD

**Issue by srimpsrimp** [rayzchen/pyeod#25]
idk what's going on here i don't code. here's a screenshot of what's happening. basically using = instead of !s makes it to where the poll has no reactions
![image](https://github.com/rayzchen/pyeod/assets/146682205/ce015dd7-ddce-4b48-b7ed-40c3db98f4a3)
![image](https://github.com/rayzchen/pyeod/assets/146682205/86d9da40-d71a-4b1b-88e1-e16e3bfdde8d)

**Comment by rayzchen** [comment]
fixed
