### ISSUE TITLE
(suggestion) Let admins change the maximum amount of elements that can be used for a combo

### ISSUE THREAD

**Issue by srimpsrimp** [rayzchen/pyeod#26]
i think it would be cool to have servers where you can only combine 2 or 9 or 3 elements, maybe even up to like 50 or 100

**Comment by Cheesy-Brik** [comment]
Couldn't go up that far as 20 is already pushing it in terms of database storage. Going lower is a good idea thought.

**Comment by steyerofoam** [comment]
is 21 elems per combo _really_ that bad tho? 5$/10 most combos aren't that much lol

**Comment by Cheesy-Brik** [comment]
https://github.com/rayzchen/pyeod/commit/f1d8fe229fc7992cbde85d186360c82e5db67d58
