### ISSUE TITLE
Get rid of the word mark in element info

### ISSUE THREAD

**Issue by glagy** [rayzchen/pyeod#34]
Look man I’m really really really sorry for doing another issue but steyerofoam told me to do this so I have to, it’s not my fault

In element info just get rid of the word Mark above the mark
That’s it you know
Bazshwoom

**Comment by rayzchen** [comment]
why

**Comment by Cheesy-Brik** [comment]
> why

Less clutter I guess

**Comment by rayzchen** [comment]
is there any need

**Comment by Cheesy-Brik** [comment]
Why did I reopen this???
