### ISSUE TITLE
Allow more complex combos with *n symbols

### ISSUE THREAD

**Issue by kylepokorski** [rayzchen/pyeod#37]
Have it so multiple *n can be used in a single combo. The total still can't exceed 21 combined elements. For example, *2 Element A+ *3 Element B would result in creating the combo for Element A+Element A+Element B+Element B+Element B.

**Comment by kylepokorski** [comment]
I know this could cause problems if elements were to start with *. Maybe those could be disabled or some other solution could be used

**Comment by rayzchen** [comment]
done
