### ISSUE TITLE
Add achievements channel

### ISSUE THREAD

**Issue by kylepokorski** [rayzchen/pyeod#45]
Achievements aren't really related to the elements themselves so shouldn't be put in #news. Maybe add a #achievements channel or not put them in #news.

**Comment by rayzchen** [comment]
EoDE posts config changes in #news as well, so this shouldn't be much of an issue.

**Comment by Cheesy-Brik** [comment]
Achievements are newsworthy. They all scale pretty quickly so it doesn't clutter news that much.
