### ISSUE TITLE
(Suggestion/Bug?) Allow what's in the image to happen

### ISSUE THREAD

**Issue by YellowCat25** [rayzchen/pyeod#46]
![pyeodsug1](https://github.com/rayzchen/pyeod/assets/107722895/6dd8c48a-43c1-47bd-b955-ccf23bade9cc)
In this image i was adding Yellow, Black, and Animal to Flower to make Bee. I used commas after the plus symbol because muscle memory and got this error. I'm not sure if it's a bug or a suggestion but I'd like commas to be used in these situations

**Comment by rayzchen** [comment]
This can't really be avoided, the plus at the beginning forces the element separator to all be +.

**Comment by Cheesy-Brik** [comment]
Yeah, closing this issue as it's literally a syntactical issue that can't be fixed.
