### ISSUE TITLE
hint isn't working + related problem

### ISSUE THREAD

**Issue by Miyuven** [rayzchen/pyeod#54]
!h eggtf
gives

/suggest + ??????????????????????????????

when combo is "*2 /suggest"

another problem that may be related:

*2 /suggest can't be combined, but making suggest, then writing *2 can

**Comment by rayzchen** [comment]
it's not broken, the element name isn't actually `/suggest`

I'll let you figure out what the element name is

**Comment by Cheesy-Brik** [comment]
> it's not broken, the element name isn't actually `/suggest`
> 
> I'll let you figure out what the element name is

Not a good response, discord changes the underlying text data that is displayed/copied to your clipboard making it extremely tedious to figure out. Should not be allowed.
