### ISSUE TITLE
Discord Formatting breaks. A lot.

### ISSUE THREAD

**Issue by srimpsrimp** [rayzchen/pyeod#56]
Caused by ``` twice in name
![image](https://github.com/rayzchen/pyeod/assets/146682205/6885cb1d-ebff-4337-89f5-8684dffe6931)
Caused by just sending = and no following text
![image](https://github.com/rayzchen/pyeod/assets/146682205/8a20f901-73f2-4ec0-b5a1-6312013c5055)
Caused by backslash in name
![image](https://github.com/rayzchen/pyeod/assets/146682205/6dcf52b6-472d-4783-8ee7-ef54c8d470ae)
Self explanatory
![image](https://github.com/rayzchen/pyeod/assets/146682205/4337028f-d33c-4cfd-b68f-b58565b3e01c)
Name greater than 251 characters causes this
![image](https://github.com/rayzchen/pyeod/assets/146682205/b6a7926e-fc69-481f-9147-1be2b4d1af44)

**Comment by srimpsrimp** [comment]
Affected elements:
#3223
#4165
#4184
#4188
#4196
#4202
#4211
#4219

**Comment by Cheesy-Brik** [comment]
All of these issues are fixed
