### ISSUE TITLE
Different discord formatting issue

### ISSUE THREAD

**Issue by Voidsans** [rayzchen/pyeod#57]
![image](https://github.com/rayzchen/pyeod/assets/70246408/d2015de5-72e2-4835-a7af-152b8068b50b)
This may look normal, but it's actually a major glitch.  Not with emojis, mind you.

You can get this glitch if you do the weird spoiler glitch which blocks all text after it, resulting in stuff like this;
![image](https://github.com/rayzchen/pyeod/assets/70246408/f131d63e-b889-4ba8-8f3b-96527dccffef)

This is what I did:
![image](https://github.com/rayzchen/pyeod/assets/70246408/5447c2b8-bb56-4bc7-aa85-8d381a1262e5)

**Comment by Cheesy-Brik** [comment]
|| bombs have been fixed
