### ISSUE TITLE
Have !c be used as a shorter !color, remove !comment, and make !m a shorter !mark

### ISSUE THREAD

**Issue by YellowCat25** [rayzchen/pyeod#65]
This is mostly because !comment being a command while everywhere else using "Mark" from polls to the slash command to the element description confuses me so I'd like to see that !comment is removed and !c is used as a shortened version of !color instead. I also want !m to be a shortened variation of !mark so that it can still be typed quickly.

**Comment by rayzchen** [comment]
Fixed with 3955d1c
