### ISSUE TITLE
Show hints for next n

### ISSUE THREAD

**Issue by azw123** [rayzchen/pyeod#69]
basically have !n x show the hints for the next x elements

**Comment by rayzchen** [comment]
not sure if this is possible because i have to rework the entire paging system, and there isn't much point in this

also each of the next x elements have multiple hints, how do I display them?

**Comment by azw123** [comment]
just show as separate messages
the only reason I want this is a qol feature so I can grind elements faster

**Comment by Cheesy-Brik** [comment]
Closing because formatting doesn't work out and separate messages would be a rate limit hell.
