### ISSUE TITLE
(Bug) Categories refusing to exist

### ISSUE THREAD

**Issue by YellowCat25** [rayzchen/pyeod#75]
![catnotworking](https://github.com/rayzchen/pyeod/assets/107722895/6912f74c-776c-4640-9f64-953d485fed81)
Categories can just unexist apparently. The same happens without slash commands.

**Comment by srimpsrimp** [comment]
this happens due to categories having capital letters in the name

**Comment by rayzchen** [comment]
Fixed with 49cfa18
