### ISSUE TITLE
Elements created after a certain time can't be viewed

### ISSUE THREAD

**Issue by kylepokorski** [rayzchen/pyeod#78]
Trying to call the info for an element with ID above #10381 results in no response from the bot. Other functions like hints can be viewed.

**Comment by kylepokorski** [comment]
Probably related to commit c2bd78d as it seems after that commit was released the issue began

**Comment by kylepokorski** [comment]
It seems this was fixed

**Comment by kylepokorski** [comment]
Seems like this is back but with higher ID elements

**Comment by Cheesy-Brik** [comment]
Seems to fixed again?

**Comment by kylepokorski** [comment]
It's back again

**Comment by kylepokorski** [comment]
@Cheesy-Brik
