### ISSUE TITLE
Achievements sync per user

### ISSUE THREAD

**Issue by srimpsrimp** [rayzchen/pyeod#89]
idk how this happened, but it does. in my new server achievements sync per user, simple as that. everyone has the same achievements. it also messes up the achievements progress menu. i'm considering just shutting down this server just because of this bug.
![image](https://github.com/rayzchen/pyeod/assets/146682205/f9adb583-8395-46d4-b4b5-41ddf44ceb92)
![image](https://github.com/rayzchen/pyeod/assets/146682205/43d736c3-089c-4fc3-bf3e-f9da4999ee68)

**Comment by Cheesy-Brik** [comment]
This was fixed
